owner: femmychat
repo: femmy-status

sites:
  - name: Conduit Client API
    url: https://c.femmy.chat/_matrix/client/versions
  - name: Conduit Federation API
    url: https://c.femmy.chat/_matrix/federation/v1/version

status-website:
  cname: demo.upptime.js.org  # Change or remove for your own custom domain
  # baseUrl: /femmy-status       # Uncomment if no custom domain, set repo name here
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: femmy-status
  introTitle: "**femmy-status** is the uptime monitor and status page for femmy.chat"
  introMessage: This status page shows real-time uptime data powered entirely by GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/femmychat/femmy-status
